Veselin_Catalogue_Shoe/Web/Controllers/ShoeCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web.Data;
using Web.Models;
using Web.Models.Shoe;

namespace Web.Controllers
{
    public class ShoeCategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShoeCategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ShoeCategories
        public async Task<IActionResult> Index()
        {
            return View(await _context.ShoeCategory.ToListAsync());
        }

        // GET: ShoeCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoeCategory = await _context.ShoeCategory
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shoeCategory == null)
            {
                return NotFound();
            }

            return View(shoeCategory);
        }

        // GET: ShoeCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ShoeCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] ShoeCategory shoeCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoeCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shoeCategory);
        }

        // GET: ShoeCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoeCategory = await _context.ShoeCategory.SingleOrDefaultAsync(m => m.Id == id);
            if (shoeCategory == null)
            {
                return NotFound();
            }
            return View(shoeCategory);
        }

        // POST: ShoeCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] ShoeCategory shoeCategory)
        {
            if (id != shoeCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoeCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoeCategoryExists(shoeCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shoeCategory);
        }

        // GET: ShoeCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoeCategory = await _context.ShoeCategory
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shoeCategory == null)
            {
                return NotFound();
            }

            return View(shoeCategory);
        }

        // POST: ShoeCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shoeCategory = await _context.ShoeCategory.SingleOrDefaultAsync(m => m.Id == id);
            _context.ShoeCategory.Remove(shoeCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShoeCategoryExists(int id)
        {
            return _context.ShoeCategory.Any(e => e.Id == id);
        }
    }
}

Veselin_Catalogue_Shoe/Web/Controllers/ShoeSizesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web.Data;
using Web.Models.Shoe;

namespace Web.Controllers
{
    public class ShoeSizesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShoeSizesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ShoeSizes
        public async Task<IActionResult> Index()
        {
            return View(await _context.ShoeSize.ToListAsync());
        }

        // GET: ShoeSizes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoeSize = await _context.ShoeSize
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shoeSize == null)
            {
                return NotFound();
            }

            return View(shoeSize);
        }

        // GET: ShoeSizes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ShoeSizes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,Details,Type,Gender")] ShoeSize shoeSize)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoeSize);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shoeSize);
        }

        // GET: ShoeSizes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoeSize = await _context.ShoeSize.SingleOrDefaultAsync(m => m.Id == id);
            if (shoeSize == null)
            {
                return NotFound();
            }
            return View(shoeSize);
        }

        // POST: ShoeSizes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,Details,Type,Gender")] ShoeSize shoeSize)
        {
            if (id != shoeSize.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoeSize);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoeSizeExists(shoeSize.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shoeSize);
        }

        // GET: ShoeSizes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoeSize = await _context.ShoeSize
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shoeSize == null)
            {
                return NotFound();
            }

            return View(shoeSize);
        }

        // POST: ShoeSizes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shoeSize = await _context.ShoeSize.SingleOrDefaultAsync(m => m.Id == id);
            _context.ShoeSize.Remove(shoeSize);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShoeSizeExists(int id)
        {
            return _context.ShoeSize.Any(e => e.Id == id);
        }
    }
}

Veselin_Catalogue_Shoe/Web/Controllers/ShoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web.Data;
using Web.Models;
using Web.Models.Shoe;
using Web.Models.ShoeViewModels;

namespace Web.Controllers
{
    public class ShoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Shoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Shoe.ToListAsync());
        }

        // GET: Shoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoe = await _context.Shoe
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shoe == null)
            {
                return NotFound();
            }

            return View(shoe);
        }

        // GET: Shoes/Create
        public IActionResult Create()
        {
            var categories = GetCategories().Select(m => new SelectListItem { Text = m.Name, Value = m.Id.ToString() });
            ViewBag.Categories = categories;

            return View();
        }

        // POST: Shoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Category")] SpecificShoeViewModel shoeViewModel)
        {
            if (ModelState.IsValid)
            {
                var categoryId = Int32.Parse(shoeViewModel.Category);

                var shoe = new SpecificShoe
                {
                    Name = shoeViewModel.Name,
                    Price = shoeViewModel.Price,
                    Category = _context.ShoeCategory.First(e => e.Id == categoryId)
                };

            _context.Add(shoe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
            return View(shoeViewModel);
    }

    // GET: Shoes/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var shoe = await _context.Shoe.SingleOrDefaultAsync(m => m.Id == id);
        if (shoe == null)
        {
            return NotFound();
        }
        return View(shoe);
    }

    // POST: Shoes/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price")] SpecificShoe shoe)
    {
        if (id != shoe.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(shoe);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ShoeExists(shoe.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(shoe);
    }

    // GET: Shoes/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var shoe = await _context.Shoe
            .SingleOrDefaultAsync(m => m.Id == id);
        if (shoe == null)
        {
            return NotFound();
        }

        return View(shoe);
    }

    // POST: Shoes/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var shoe = await _context.Shoe.SingleOrDefaultAsync(m => m.Id == id);
        _context.Shoe.Remove(shoe);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool ShoeExists(int id)
    {
        return _context.Shoe.Any(e => e.Id == id);
    }

    public IEnumerable<ShoeCategory> GetCategories()
    {
        var categories = _context.ShoeCategory.ToList();

        return categories;
    }
}
}

Veselin_Catalogue_Shoe/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Каталог за обуки</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
		<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
		<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
		<!-- Nucleo Icons -->
		<link href="~/css/nucleo-icons.css" rel="stylesheet" />
		<!-- CSS Files -->
		<link href="~/css/blk-design-system.css?v=1.0.0" rel="stylesheet" />
		<!-- CSS Just for demo purpose, don't include it in your project -->
		<link href="~/css/demo/demo.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg bg-info navbar-fixed-top">
			<div class="container">
				<div class="navbar-translate">
					<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
						<img style="max-width: 56px;" src="~/images/logo.png" />
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#example-navbar-info" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="sr-only">Каталог за обувки</span>
						<span class="navbar-toggler-bar bar1"></span>
						<span class="navbar-toggler-bar bar2"></span>
						<span class="navbar-toggler-bar bar3"></span>
					</button>
				</div>
			<div class="collapse navbar-collapse" id="example-navbar-info">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Начало</a></li>
						<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Shoes" asp-action="Index">Обучки</a></li>
						<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="ShoeCategory" asp-action="Index">Категории</a></li>
						<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="ShoeSizes" asp-action="Index">Номерация</a></li>
						<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Home" asp-action="About">За проекта</a></li>
						<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Контакти</a></li>
					</ul>
					@await Html.PartialAsync("_LoginPartial")
				</div>
			</div>
		</nav>
	</header>
    <div class="container body-content">
		<main>
        	@RenderBody()
		</main>
		
    </div>
	<footer class="footer">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-md-4">
						<img style="max-width: 156px;" src="~/images/logo.png" />
					</div>
					<div class="col-md-4">
						<nav class="navbar bg-none">
							<ul class="navbar-nav mr-auto">
								<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Начало</a></li>
								<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Shoes" asp-action="Index">Обучки</a></li>
								<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="ShoeCategories" asp-action="Index">Категории</a></li>
								<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Home" asp-action="About">За проекта</a></li>
								<li class="nav-item" ><a  class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Контакти</a></li>
							</ul>
						</nav>
					</div>
					<div class="col-md-4">
						<h3 class="title">Последвай ме:</h3>
						<div class="btn-wrapper profile">
							<a target="_blank" href="https://www.facebook.com/vbeev?ref=bookmarks" class="btn btn-icon btn-neutral btn-round btn-simple" data-toggle="tooltip" data-original-title="Like us">
								<i class="fab fa-facebook-square"></i>
							</a>
							<a target="_blank" href="https://www.linkedin.com/in/veselin-beev-b8a040b7/" class="btn btn-icon btn-neutral  btn-round btn-simple" data-toggle="tooltip" data-original-title="Follow us">
								<i class="fab fa-linkedin"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
      
    </environment>

	<script src="~/js/core/jquery.min.js" type="text/javascript"></script>
	<script src="~/js/core/popper.min.js" type="text/javascript"></script>
	<script src="~/js/core/bootstrap.min.js" type="text/javascript"></script>
	<script src="~/js/plugins/perfect-scrollbar.jquery.min.js"></script>
	<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
	<script src="~/js/plugins/bootstrap-switch.js"></script>
	<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
	<script src="~/js/plugins/nouislider.min.js" type="text/javascript"></script>
	<!-- Chart JS -->
	<script src="~/js/plugins/chartjs.min.js"></script>
	<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
	<script src="~/js/plugins/moment.min.js"></script>
	<script src="~/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
	<!-- Black Dashboard DEMO methods, don't include it in your project! -->
	<script src="~/js/demo/demo.js"></script>
	<!-- Control Center for Black UI Kit: parallax effects, scripts for the example pages etc -->
	<script src="~/js/blk-design-system.min.js?v=1.0.0" type="text/javascript"></script>
	<script>
		$(document).ready(function() {
			blackKit.initDatePicker();
			blackKit.initSliders();
		});

		function scrollToDownload() {

			if ($('.section-download').length != 0) {
			$("html, body").animate({
				scrollTop: $('.section-download').offset().top
			}, 1000);
			}
		}
	</script>
    @RenderSection("Scripts", required: false)
</body>
</html>